spring:
  datasource:
    url: ${SHORT_URL_DATABASE_URL}
    username: ${SHORT_URL_DATABASE_USER}
    password: ${SHORT_URL_DATABASE_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false